/**
 * Tokens de diseño del sistema "Verdure Clínica".
 * Paleta verde profundo con acento ámbar dorado.
 * Tipografía: Fraunces (display) + Outfit (body).
 */
export const colors = {
  primary:      '#15423a',
  primaryHover: '#1d5e52',
  primaryLight: '#e8f2ef',
  primaryMid:   '#2d7165',
  accent:       '#c8945a',
  accentLight:  '#fef3e8',
  secondary:    '#4d7a6e',
  success:      '#15803d',
  danger:       '#be123c',
  warning:      '#b45309',
  info:         '#0369a1',
  background:   '#f0f5f2',
  surface:      '#ffffff',
  surfaceAlt:   '#f5faf7',
  border:       '#cce0d9',
  borderLight:  '#e3eeeb',
  text:         '#0f2b24',
  textLight:    '#4d7a6e',
};

export const fonts = {
  display: "'Fraunces', Georgia, serif",
  body:    "'Outfit', system-ui, sans-serif",
};

export const css = {
  card: {
    background: colors.surface,
    borderRadius: 12,
    border: `1px solid ${colors.borderLight}`,
    padding: '24px',
    boxShadow: '0 1px 4px rgba(15,43,36,0.08)',
  },
  cardCompact: {
    background: colors.surface,
    borderRadius: 12,
    border: `1px solid ${colors.borderLight}`,
    padding: '16px 20px',
    boxShadow: '0 1px 4px rgba(15,43,36,0.08)',
  },
  btnPrimary: {
    background: colors.primary,
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    padding: '11px 22px',
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 600,
    fontFamily: fonts.body,
    boxShadow: '0 2px 8px rgba(21,66,58,0.25)',
    transition: 'background 0.2s ease, box-shadow 0.2s ease',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  btnDanger: {
    background: colors.danger,
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    padding: '8px 18px',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 600,
    fontFamily: fonts.body,
    transition: 'background 0.2s ease',
  },
  btnSecondary: {
    background: colors.primaryLight,
    color: colors.primary,
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    padding: '8px 18px',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 500,
    fontFamily: fonts.body,
    transition: 'background 0.2s ease',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  btnGhost: {
    background: 'transparent',
    color: colors.textLight,
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    padding: '8px 16px',
    cursor: 'pointer',
    fontSize: 13,
    fontFamily: fonts.body,
    transition: 'all 0.2s ease',
  },
  input: {
    width: '100%',
    padding: '11px 14px',
    border: `1.5px solid ${colors.border}`,
    borderRadius: 8,
    fontSize: 14,
    fontFamily: fonts.body,
    color: colors.text,
    outline: 'none',
    boxSizing: 'border-box',
    background: colors.surface,
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
  },
  label: {
    display: 'block',
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
    color: colors.textLight,
    marginBottom: 6,
    fontFamily: fonts.body,
  },
  sectionTitle: {
    fontFamily: fonts.display,
    fontSize: 20,
    fontWeight: 600,
    color: colors.text,
    margin: '0 0 16px',
  },
  pageTitle: {
    fontFamily: fonts.display,
    fontSize: 26,
    fontWeight: 700,
    color: colors.text,
    margin: '0 0 4px',
  },
};
